// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aybzgswmfyatnavnhuyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5Ynpnc3dtZnlhdG5hdm5odXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MjExODYsImV4cCI6MjA2NjM5NzE4Nn0.WMG9CP6swi5gbNIZgITNupA9gMz-Pic0lX0ByfL6cqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);